CREATE TABLE IF NOT EXISTS `SATVocabularyList2` (
`definition` VARCHAR(MAX) NULL,
`type` VARCHAR(MAX) NULL,
`word` VARCHAR(MAX) NULL
);

INSERT INTO SATVocabularyList2 VALUES
('hate','','Abhor'),
('narrow-minded\, prejudiced person','','Bigot'),
('fake; false','','Counterfeit'),
('give voting rights','','Enfranchise'),
('hinder; obstruct','','Hamper'),
('to start a fire','','Kindle'),
('harmful; poisonous; lethal','','Noxious'),
('calm; peaceful','','Placid'),
('payment for work done','','Remuneration'),
('lucky charm','','Talisman'),
('rough; coarse; harsh','','Abrasive'),
('cheat; defraud','','Bilk'),
('hidden; undercover','','Covert'),
('cause','','Engender'),
('storage area (like garage) for a plane','','Hangar'),
('complex; difficult to solve','','Knotty'),
('something subtle; a fine shade of meaning','','Nuance'),
('taking credit for someone else''s writing or ideas','','Plagiarism'),
('fame','','Renown'),
('going off the main subject','','Tangent'),
('humiliation; degradation','','Abasement'),
('swelling; fluttering; waving','','Billowing'),
('recoil in fear or servility; shrink away from','','Cower'),
('improve; make better or clearer','','Enhance'),
('noisy\, attacking speech','','Harangue'),
('a maze','','Labyrinth'),
('to counter; make unimportant','','Nullify'),
('petitioner (in court of law)','','Plaintiff'),
('full','','Replete'),
('can be touched','','Tangible'),
('cancel; deny; repeal','','Abrogate'),
('speech which offends religious sentiments','','Blasphemy'),
('believable','','Credible'),
('puzzle; mystery','','Enigma'),
('indicators; bringers of warnings','','Harbingers'),
('complicated; highly convoluted','','Labyrinthine'),
('cuddle; snuggle','','Nuzzle'),
('statement giving strong praise','','Plaudit'),
('shameful; very bad','','Reprehensible'),
('slow; late; overdue; delayed','','Tardy'),
('forgiveness; pardon; release','','Absolution'),
('obvious','','Blatant'),
('praiseworthy','','Creditable'),
('establish firmly in a position','','Ensconce'),
('hurry; accelerate; rush','','Hasten'),
('a cut','','Laceration'),
('stubborn','','Obdurate'),
('can be believed; reasonable','','Plausible'),
('a respite; postponement of a sentence','','Reprieve'),
('of little value; gaudy','','Tawdry'),
('desist; go without; withdraw','','Abstain'),
('damaged; destroyed; ruined','','Blighted'),
('gullible; ready to believe anything','','Credulous'),
('cover','','Enshroud'),
('arrogance; pride','','Haughtiness'),
('tearful; sad','','Lachrymose'),
('deliberately make something difficult to understand','','Obfuscate'),
('an excess','','Plethora'),
('shun; eschew','','Repudiate'),
('boredom','','Tedium'),
('self denying; refraining from indulging','','Abstemious'),
('free-spirited; carefree','','Blithe'),
('active at dawn and dusk','','Crepuscular'),
('clear pronunciation; accent; articulation','','Enunciation'),
('stubborn; willful','','Headstrong'),
('dull; monotonous; bland','','Lackluster'),
('unbiased; not subjective','','Objective'),
('flexible; not stubborn','','Pliable'),
('retract; repeal','','Rescind'),
('to moderate; soften','','Temper'),
('difficult to understand; obscure','','Abstruse'),
('1. ancient weapon (type of gun); 2. a clumsy person','','Blunderbuss'),
('recoil; flinch; shy away','','Cringe'),
('to cause bitterness and bad feeling','','Envenom'),
('self indulgence; pleasure-seeking','','Hedonism'),
('using few words; brief; to the point','','Laconic'),
('indirect; slanting','','Oblique'),
('feathers of a bird','','Plumage'),
('acceptance of fate','','Resignation'),
('stubborn; resolute; holding firm to a purpose','','Tenacious'),
('tribute; honor; praise','','Accolade'),
('support; prop up','','Bolster'),
('puzzling; enigmatic','','Cryptic'),
('short-lived','','Ephemeral'),
('a pleasure seeker','','Hedonist'),
('expression of regret or sorrow','','Lamentation'),
('destroy; demolish; eradicate','','Obliterate'),
('fall suddenly and steeply','','Plummet'),
('determination','','Resolution'),
('not certain','','Tentative'),
('to agree to; give in to','','Acquiesce'),
('arrogant\, pompous language','','Bombast'),
('cut short','','Curtail'),
('someone who appreciates good food and drink','','Epicure'),
('listen to','','Heed'),
('ridicule; spoof','','Lampoon'),
('totally unaware','','Oblivious'),
('raised platform','','Podium'),
('echoing','','Resonant'),
('flimsy; not solid','','Tenuous'),
('sharp; pungent (used of smells and tastes)','','Acrid'),
('ill-mannered','','Boorish'),
('believing that people act only out of selfish motives','','Cynical'),
('a letter (form of communication)','','Epistle'),
('against orthodox opinion','','Heresy'),
('spear; spike; javelin','','Lance'),
('difficult to understand; partially hidden','','Obscure'),
('deeply moving; strongly affecting the emotions','','Poignant'),
('a break; intermission','','Respite'),
('concise; to the point','','Terse'),
('fear of heights','','Acrophobia'),
('middle class','','Bourgeois'),
('weakness; incapacity','','Debility'),
('concerned with letters; through correspondence','','Epistolary'),
('interruption; pause','','Hiatus'),
('tired; slow','','Languid'),
('hidden; covered; buried','','Obscured'),
('calm; collected; self-possessed','','Poised'),
('shining; glowing','','Resplendent'),
('medicinal; curative','','Therapeutic'),
('sharpness (mental or visual)','','Acuity'),
('someone who boasts','','Braggart'),
('exposing false claims or myths','','Debunking'),
('typified; characterized; personified','','Epitomized'),
('rigid in opinions','','Hidebound'),
('decay; fade away; get weaker','','Languish'),
('servile; submissive','','Obsequious'),
('causing debate or argument','','Polemical'),
('a tonic','','Restorative'),
('prevent; frustrate','','Thwart'),
('forceful; inflexible','','Adamant'),
('muscular','','Brawny'),
('an athletic competition with ten events','','Decathlon'),
('speak ambiguously; avoid telling the truth','','Equivocate'),
('1. picture writing; 2. writing which is difficult to read or enigmatic','','Hieroglyphics'),
('theft; robbery; stealing','','Larceny'),
('a dominating concern','','Obsession'),
('weighty; slow and heavy','','Ponderous'),
('preservation; withholding','','Retention'),
('cowardly; fearful','','Timorous'),
('skilful / skillful','','Adroit'),
('being brief','','Brevity'),
('dignified\, correct behavior [','','Decorum'),
(']','','Err'),
('make a mistake','','Hinder'),
('obstruct','','Largess'),
('generosity','','Obsolete'),
('no longer valid','','Pontificate'),
('speak pompously or dogmatically','','Reticent'),
('restrained; holding something back; uncommunicative','','Tirade'),
('stream of verbal abuse','','Adulation'),
('strong admiration; worship','','Bristle'),
('to show irritation','','Decoy'),
('lure; trap; trick','','Erratic'),
('wandering; irregular','','Histrionic'),
('theatrical; exaggerated','','Laud'),
('praise','','Obstreperous'),
('noisy and boisterous','','Portend'),
('foretell','','Retraction'),
('withdrawal; cancellation of a statement','','Titter'),
('giggle quietly','','Adversity'),
('hardship','','Broach'),
('start to discuss; approach','','Deference'),
('respect','','Esoteric'),
('obscure and difficult to understand','','Hoary'),
('old','','Lavish'),
('on a grand scale; wasteful','','Obtuse'),
('mentally dull','','Portent'),
('a warning sign; omen','','Revere'),
('worship','','Tome'),
('large book','','Advocate'),
('support','','Brusque'),
('blunt; abrupt','','Defoliate'),
('cause leaves to fall off','','Espouse'),
('promote; take up; support','','Hone'),
('sharpen; increase; whet','','Lax'),
('careless; not strict','','Obviate'),
('avoid; make unnecessary','','Poseur'),
('someone who puts on an act','','Riddled'),
('full of (usually full of holes)','','Torpid'),
('inactive; lazy; stagnant','','Aesthetic'),
('concerning art or beauty','','Bulwark'),
('fortification; barricade; wall','','Defunct'),
('no longer in existence','','Etymology'),
('the study of word origins','','Hyperbole'),
('grossly exaggerated speech','','Legend'),
('1. key to map;  2. myth or story','','Odious'),
('hateful','','Posterity'),
('future generations','','Rife'),
('common','','Torpor'),
('dormancy; sluggishness; inactivity','','Affable'),
('friendly; social; easygoing','','Bureaucracy'),
('officialdom','','Degradation'),
('deprivation; poverty; debasement','','Eulogy'),
('praise','','Hypochondriac'),
('a person obsessed with health; having imaginary illnesses','','Legion'),
('in large numbers','','Officious'),
('domineering; intrusive; meddlesome','','Posthumous'),
('after death','','Rigor'),
('thoroughness','','Totter'),
('eagerness; enthusiasm; quickness','','Alacrity'),
('grow; flourish; put forth new shoots','','Burgeon'),
('harmful','','Deleterious'),
('a polite phrase to cover something unpleasant','','Euphemism'),
('insincere','','Hypocritical'),
('tired; without energy','','Lethargic'),
('stare at; observe in an obvious manner','','Ogle'),
('hypothesize; propose','','Postulate'),
('strong; healthy; tough','','Robust'),
('obedient; dutiful; polite','','Tractable'),
('medieval chemistry; attempt to change base metal into gold','','Alchemy'),
('polish','','Burnish'),
('to think over deeply','','Deliberate'),
('pleasant sounds','','Euphony'),
('person who opposes orthodoxy','','Iconoclast'),
('flippancy; joking about serious matters','','Levity'),
('concerned with the sense of smell','','Olfactory'),
('suitable for drinking','','Potable'),
('round','','Rotund'),
('peaceful','','Tranquil'),
('an excuse that shows someone was not at a crime scene','','Alibi'),
('strengthen; support','','Buttress'),
('demarcation; explanation; definition; outlining','','Delineation'),
('vacate; empty; abandon','','Evacuate'),
('a personal peculiarity; something unique to an individual','','Idiosyncrasy'),
('someone who opposes tyranny','','Libertarian'),
('threatening','','Ominous'),
('powerful; compelling; strong','','Potent'),
('think over something; ponder','','Ruminate'),
('copy','','Transcribe'),
('to lessen','','Allay'),
('the line that tells you who wrote an article','','Byline'),
('hesitate; refuse','','Demur'),
('make worse','','Exacerbate'),
('shameful','','Ignominious'),
('soothing lotion','','Liniment'),
('all-powerful','','Omnipotent'),
('practical','','Pragmatic'),
('trick; stratagem','','Ruse'),
('go astray; disobey; commit a sin','','Transgress'),
('make less severe','','Alleviate'),
('discordant loud noises','','Cacophony'),
('condemn; speak out against','','Denounce'),
('frustrated; annoyed','','Exasperated'),
('shame [','','Ignominy'),
(']','','Lithe'),
('flexible; supple','','Omniscient'),
('all-knowing','','Pragmatist'),
('practical person; one who is concerned with usefulness','','Saccharin'),
('falsely sweet','','Transient'),
('short-lived; ephemeral','','Aloof'),
('distant; detached; cold','','Cajole'),
('coax','','Deplete'),
('use up; lessen','','Exceptionable'),
('very bad (something which we should object to)','','Illuminate'),
('to light up or make clear','','Livid'),
('very angry','','Onerous'),
('burdensome; hard to undertake','','Preamble'),
('introductory material','','Sacrosanct'),
('very holy; inviolable','','Traverse'),
('to move across','','Altruism'),
('putting others first; being self-sacrificing','','Caldron'),
('huge cooking pot','','Deplore'),
('regret','','Exculpate'),
('free someone from blame; pardon; acquit','','Illusory'),
('deceptive; false; misleading','','Lobbyist'),
('person who tries to persuade someone to support a particular cause','','Onus'),
('burden','','Precarious'),
('unstable; risky','','Sagacious'),
('wise','','Trepidation'),
('fear','','Amass'),
('accumulate','','Callow'),
('immature','','Depravity'),
('moral corruption','','Execrable'),
('very\, very bad','','Immoderate'),
('excessive; extreme','','Lofty'),
('snooty; arrogant; haughty','','Opaque'),
('does not let light through','','Precedent'),
('a previous occurrence used as a guide','','Sage'),
('a wise person','','Trinket'),
('something of little value; knick-knack','','Ambiguity'),
('uncertainty; vagueness','','Candid'),
('frank; honest','','Deprecate'),
('criticize; denounce','','Exegesis'),
('scholarly explanation or interpretation','','Immutable'),
('unchanging; permanent','','Longevity'),
('long life','','Opulent'),
('wealthy; rich; magnificent','','Precept'),
('guiding principle','','Salacious'),
('lecherous; erotic','','Trite'),
('unoriginal; dull','','Ambiguous'),
('unclear in meaning; can be interpreted in different ways','','Candor'),
('frankness; openness','','Deride'),
('ridicule; make fun of; mock','','Exemplary'),
('outstandingly good; setting a fine example','','Impartial'),
('unbiased; neutral','','Loquacious'),
('talkative','','Ordain'),
('1. destine; 2. confer holy orders on a priest','','Precinct'),
('district of a city','','Sallow'),
('yellowish','','Trivial'),
('lack of clarity; wavering; being undecided','','Ambivalence'),
('bad-tempered; quarrelsome','','Cantankerous'),
('uncomplimentary','','Derogatory'),
('to serve as a good example','','Exemplify'),
('having no money','','Impecunious'),
('clear','','Lucid'),
('highly decorated','','Ornate'),
('steep slope','','Precipice'),
('health-giving','','Salubrious'),
('shirker; someone absent without permission','','Truant'),
('able to walk around (used of hospital patients)','','Ambulatory'),
('spacious','','Capacious'),
('to damage or pollute a holy place','','Desecrate'),
('complete and thorough','','Exhaustive'),
('wicked; profane','','Impious'),
('ridiculous; silly','','Ludicrous'),
('conventional','','Orthodox'),
('done in a hurry','','Precipitous'),
('something which teaches you a lesson; beneficial','','Salutary'),
('cut short','','Truncate'),
('make better','','Ameliorate'),
('surrender; give in to','','Capitulate'),
('spoiling something holy','','Desecration'),
('acquits; absolves; removes blame','','Exonerates'),
('destitute; poor','','Impoverished'),
('1. unenthusiastic; 2. neither hot nor cold','','Lukewarm'),
('1. turn to bone; 2. become fixed and rigid','','Ossify'),
('prevent or make impossible','','Preclude'),
('hypocritically holy','','Sanctimonious'),
('uproar; noise','','Tumult'),
('improvement','','Amelioration'),
('constant criticism','','Carping'),
('stop; discontinue; cease','','Desist'),
('getting free/rid of; eliminating (especially demons)','','Exorcism'),
('unrehearsed; spontaneous','','Impromptu'),
('clumsy person','','Lummox'),
('showy','','Ostentatious'),
('developing early','','Precocious'),
('give approval to','','Sanction'),
('depravity','','Turpitude'),
('friendly','','Amiable'),
('person who makes maps','','Cartographer'),
('having no hope; miserable','','Despondent'),
('refugee; emigrant; someone living away from his own country','','Expatriate'),
('not intentional','','Inadvertent'),
('juicy; moist; succulent','','Luscious'),
('push out of a position','','Oust'),
('one who came before','','Predecessor'),
('bloodthirsty; bloody','','Sanguinary'),
('novice; beginner','','Tyro'),
('friendship','','Amity'),
('scold strongly','','Castigate'),
('hardship; poverty; misery','','Destitution'),
('convenient; practical','','Expedient'),
('chant; invocation; prayer','','Incantation'),
('assassinate; kill; illegal hanging','','Lynch'),
('obvious; not hidden','','Overt'),
('dilemma; difficult situation','','Predicament'),
('optimistic; cheerful','','Sanguine'),
('found everywhere; omnipresent','','Ubiquitous'),
('lacking in shape','','Amorphous'),
('purging of pent-up emotions','','Catharsis'),
('put off; prevent','','Deter'),
('make faster','','Expedite'),
('putting in prison','','Incarceration'),
('plots and plans','','Machinations'),
('worked up; in an emotional state','','Overwrought'),
('famous; outstanding','','Preeminent'),
('mocking','','Sardonic'),
('undiluted; total','','Unalloyed'),
('medicine to combat pain','','Analgesic'),
('type of private political meeting','','Caucus'),
('worsen; decline','','Deteriorate'),
('clear explanation','','Exposition'),
('without stopping','','Incessant'),
('whirlpool; storm in the ocean','','Maelstrom'),
('good to eat; agreeable','','Palatable'),
('right or privilege','','Prerogative'),
('person with knowledge','','Savant'),
('oily; using excessive flattery','','Unctuous'),
('comparable','','Analogous'),
('burning','','Caustic'),
('harmful','','Detrimental'),
('praise','','Extol'),
('just beginning','','Incipient'),
('generous; big-hearted','','Magnanimous'),
('fence made of posts','','Palisade'),
('having fore-knowledge','','Prescient'),
('to climb','','Scale'),
('damaged; attacked','','Undermined'),
('chaos; lack of government','','Anarchy'),
('procession of vehicles','','Cavalcade'),
('greedily eaten/consumed','','Devoured'),
('deport from one country back to the home country','','Extradite'),
('tendency; a leaning toward','','Inclination'),
('powerful businessman','','Magnate'),
('a remedy that improves but doesn''t cure','','Palliative'),
('a feeling that something might happen','','Presentiment'),
('person on whom blame is placed for faults of others','','Scapegoat'),
('emphasize','','Underscore'),
('a brief amusing story','','Anecdote'),
('speed','','Celerity'),
('skilful with hands','','Dexterous'),
('irrelevant','','Extraneous'),
('not clear','','Incoherent'),
('clumsy; unskillful','','Maladroit'),
('pale','','Pallid'),
('assuming too much; arrogant','','Presumptuous'),
('careful; diligent; painstaking','','Scrupulous'),
('clear; obvious','','Unequivocal'),
('hatred; antagonism','','Animosity'),
('disapproving; critical','','Censorious'),
('a division into two parts','','Dichotomy'),
('extend; predict on the basis of known data','','Extrapolate'),
('not fitting in; out of place','','Incongruous'),
('illness','','Malady'),
('easily felt; easily perceived','','Palpable'),
('pompous; self-important','','Pretentious'),
('examine carefully','','Scrutinize'),
('set free','','Unfetter'),
('a building which is an addition to an existing building','','Annex '),
('blame','','Censure'),
('intended to teach; instructive','','Didactic'),
('irrelevant; on the outside','','Extrinsic'),
('unimportant; insignificant; negligible','','Inconsequential'),
('a curse','','Malediction'),
('remedy for all ills','','Panacea'),
('speak misleadingly and evasively','','Prevaricate'),
('sink','','Scuttle'),
('to remove a priest from his position','','Unfrock'),
('take possession of; seize; capture','','Annex '),
('intellectual','','Cerebral'),
('lacking confidence','','Diffident'),
('false','','Fallacious'),
('not easily seen; subtle; not noticeable','','Inconspicuous'),
('a wrong-doer','','Malefactor'),
('1. example; 2. model; 3. way of looking at things','','Paradigm'),
('unspoiled','','Pristine'),
('an institution in which priests are trained','','Seminary'),
('never having happened before','','Unprecedented'),
('something which does not fit in a pattern; irregularity','','Anomaly'),
('certainty','','Certitude'),
('wander off the subject','','Digress'),
('hesitate; waver','','Falter'),
('cannot be wiped out','','Indelible'),
('deliberately avoid work; shirk','','Malinger'),
('apparently contradictory statement','','Paradox'),
('tendency towards','','Proclivity'),
('appealing to the senses','','Sensuous'),
('unharmed; intact; without a scratch','','Unscathed'),
('hostility; strong opposition','','Antagonism'),
('trickster who claims knowledge he doesn''t have','','Charlatan'),
('dam; embankment','','Dike'),
('obsessive; fixated','','Fanatical'),
('1. neutral;  2. not outstanding','','Indifferent'),
('person who deliberately tries to avoid work','','Malingerer'),
('a perfect example','','Paragon'),
('delay; put off','','Procrastinate'),
('guard; sentry','','Sentinel'),
('not deliberate; unconscious','','Unwitting'),
('opposed; hostile; aggressive','','Antagonistic'),
('wary of; cautious about; reluctant to give','','Chary'),
('slow; falling behind with one''s work','','Dilatory'),
('passion; excessive devotion','','Fanaticism'),
('native to a particular area','','Indigenous'),
('flexible; can be shaped','','Malleable'),
('of supreme importance','','Paramount'),
('wasteful; extravagant','','Prodigal'),
('isolate','','Sequester'),
('scold; tell off; reprimand','','Upbraid'),
('outdated; prehistoric; very old-fashioned','','Antediluvian'),
('punishes','','Chastises'),
('puzzling situation','','Dilemma'),
('overly particular; finicky','','Fastidious'),
('laziness','','Indolence'),
('1. wooden hammer; 2. stick used for polo','','Mallet'),
('1. scrounger; 2. animal which takes digested food from another','','Parasite'),
('very large','','Prodigious'),
('fortunate coincidence; unsought discovery','','Serendipity'),
('hilarious; hysterical; very funny','','Uproarious'),
('a book which is a collection of poems or stories','','Anthology'),
('trickery','','Chicanery'),
('person who dabbles in a subject without serious study','','Dilettante'),
('silly; foolish','','Fatuous'),
('novice; beginner','','Inductee'),
('influencable; controllable','','Manipulatable'),
('dried up','','Parched'),
('unholy','','Profane'),
('calm; peaceful','','Serene'),
('outcome','','Upshot'),
('putting man at the center of one''s philosophy','','Anthropocentrism'),
('changeable; unstable','','Chimerical'),
('hard-working','','Diligent'),
('possible and practicable','','Feasible'),
('pampering; satisfying desires','','Indulgent'),
('damaged; spoiled','','Marred'),
('an outcast from society','','Pariah'),
('swearing; cursing','','Profanity'),
('jagged; saw-like','','Serrated'),
('sophisticated; suave','','Urbane'),
('outdated; old fashioned','','Antiquated'),
('easily angered','','Choleric'),
('model of a scene','','Diorama'),
('fertile','','Fecund'),
('drunkenness; intoxication','','Inebriation'),
('to gather together','','Marshal'),
('equality','','Parity'),
('having deep meaning','','Profound'),
('overly submissive; groveling','','Servile'),
('take someone''s position (usually by force)','','Usurp'),
('indifferent; uninterested; lethargic','','Apathetic'),
('person who records historical information','','Chronicler'),
('mournful song','','Dirge'),
('apt','','Felicitous'),
('cannot be expressed in words','','Ineffable'),
('pouched mammal (like a kangaroo)','','Marsupial'),
('narrow-minded; concerned only with local matters','','Parochial'),
('depth','','Profundity'),
('doubting; not gullible','','Skeptical'),
('useful','','Utilitarian'),
('lack of interest or emotion','','Apathy'),
('indirect','','Circuitous'),
('disapproval','','Disapprobation'),
('passion; enthusiasm','','Fervor'),
('incompetent; unskilled; useless','','Inept'),
('person who believes in strict discipline','','Martinet'),
('a mockery; imitation for ridicule; spoof','','Parody'),
('member of the working class','','Proletarian'),
('minor battle','','Skirmish'),
('a believer in an ideal world','','Utopian'),
('of doubtful origin','','Apocryphal'),
('using too many words; long-windedness','','Circumlocution'),
('to distinguish one thing from another','','Discern'),
('unpredictable; whimsical; easily swayed','','Fickle'),
('inactivity; lethargy','','Inertia'),
('person who intentionally inflicts pain on himself','','Masochist'),
('ward off; avoid','','Parry'),
('producing a lot','','Prolific'),
('slow-moving; lethargic person','','Sluggard'),
('waver; hesitate','','Vacillate'),
('pacify; soothe; calm down; make peace with','','Appease'),
('limit','','Circumscribe'),
('disagreement','','Discord'),
('skill','','Finesse'),
('cannot be avoided','','Inevitable'),
('society governed by women','','Matriarchy'),
('economical; frugal; thrifty','','Parsimonious'),
('promoters; supporters','','Proponents'),
('refine an ore','','Smelt'),
('empty; silly; meaningless','','Vacuous'),
('worried; fearful','','Apprehensive'),
('cautious; considering all sides','','Circumspect'),
('cacophony; harshness; jarring','','Discordancy'),
('not continuous; stopping and starting','','Fitful'),
('relentless','','Inexorable'),
('a loner','','Maverick'),
('stinginess; frugality; cost-cutting','','Parsimony'),
('dull; boring; ordinary','','Prosaic'),
('a Swedish buffet of cold dishes','','Smorgasbord'),
('person wandering without a home','','Vagrant'),
('can be cultivated','','Arable'),
('avoid','','Circumvent'),
('something which does not match up; inconsistency','','Discrepancy'),
('clearly wrong','','Flagrant'),
('not advisable','','Inexpedient'),
('in short supply','','Meager'),
('biased; one-sided; committed to one group','','Partisan'),
('forbid','','Proscribe'),
('comfort for grief','','Solace'),
('dull; uninspiring','','Vapid'),
('random; for no definite reason','','Arbitrary'),
('psychic; mystic','','Clairvoyant'),
('to make a clear distinction; see the difference','','Discriminate'),
('showy; ornate','','Flamboyant'),
('perfect; flawless; cannot make mistakes','','Infallible'),
('wander from side to side','','Meander'),
('evoking sadness or pity','','Pathos'),
('study of versification','','Prosody'),
('to ask for; seek','','Solicit'),
('multicolored; speckled','','Variegated'),
('obscure; known only to a few people','','Arcane'),
('shout; scream','','Clamor'),
('long windedness; indirectness','','Discursiveness'),
('show off; display in a showy manner','','Flaunt'),
('famous for something bad','','Infamous'),
('soft; melodious; ripe','','Mellow'),
('one who give support (usually financial)','','Patron'),
('1. lying face down; 2. be overcome with extreme weakness','','Prostration'),
('sleepwalker','','Somnambulist'),
('violence; fervor; forcefulness','','Vehemence'),
('ancient; outdated; old fashioned','','Archaic'),
('secret; covert; stealthy','','Clandestine'),
('contempt; strong dislike','','Disdain'),
('making jokes about serious matters','','Flippant'),
('deduce; conclude','','Infer'),
('collection of animals','','Menagerie'),
('condescend to; behave in an arrogant manner towards','','Patronize'),
('main character in film\, book\, play etc.','','Protagonist'),
('fortuneteller','','Soothsayer'),
('forceful','','Vehement'),
('classic example of','','Archetype'),
('mercy','','Clemency'),
('unbiased','','Disinterested'),
('defy; reject','','Flout'),
('naïve\, unsophisticated person','','Ingénue'),
('given to lying','','Mendacious'),
('shortage','','Paucity'),
('changeable','','Protean'),
('juvenile; immature','','Sophomoric'),
('corrupt; can be bribed','','Venal'),
('collections of old records; place of storage of old documents','','Archives'),
('overused expression; something unoriginal','','Cliché'),
('criticize; belittle','','Disparage'),
('worked-up; not calm','','Flustered'),
('ungrateful person','','Ingrate'),
('concerned only with money','','Mercenary'),
('minor weakness; trivial offence','','Peccadillo'),
('person under protection of\, or guided by another','','Protégé'),
('inducing sleep','','Soporific'),
('surface coating','','Veneer'),
('clear; lucid; eloquent','','Articulate'),
('customers','','Clientele'),
('an inequality','','Disparity'),
('unreliable; disreputable','','Fly-by-night'),
('hostile','','Inimical'),
('volatile; changeable','','Mercurial'),
('person who insists on strict adherence to rules or narrow learning','','Pedant'),
('procedure; code of behavior','','Protocol'),
('spare; bare; meager','','Sparse'),
('revere; worship','','Venerate'),
('deception; trickery','','Artifice'),
('come together; merge','','Coalesce'),
('neutral; objective','','Dispassionate'),
('concerned with argument or debate (esp. for legal evidence)','','Forensic'),
('inherited; inborn','','Innate'),
('come together','','Merge'),
('common; mundane; banal','','Pedestrian'),
('unsophisticated; narrow-minded','','Provincial'),
('false','','Specious'),
('minor; unimportant','','Venial'),
('craftsman','','Artisan'),
('pamper; fuss over; indulge','','Coddle'),
('circulating; broadcasting; spreading (information)','','Disseminating'),
('bravery','','Fortitude'),
('harmless; inoffensive','','Innocuous'),
('symbolically; figuratively','','Metaphorically'),
('without equal','','Peerless'),
('cautious; wise','','Prudent'),
('spotted; freckled; dotted','','Speckled'),
('truthfulness','','Veracity'),
('without luxuries; severely simple','','Ascetic'),
('force','','Coercion'),
('active in daytime','','Diurnal'),
('happening by chance','','Fortuitous'),
('create; introduce something new','','Innovate'),
('very careful; painstaking','','Meticulous'),
('derogatory','','Pejorative'),
('childish','','Puerile'),
('not continuous; intermittent','','Sporadic'),
('talkative; long-winded; rambling','','Verbose'),
('thorough; diligent','','Assiduous'),
('lucid; well argued','','Cogent'),
('1. entertain; 2. distract; 3. cause a detour','','Divert'),
('irritable; difficult to control','','Fractious'),
('mysterious; impenetrable','','Inscrutable'),
('courage; bravery; valor','','Mettle'),
('transparently clear','','Pellucid'),
('paying attention to small details','','Punctilious'),
('false','','Spurious'),
('using too many words','','Verbosity'),
('to calm','','Assuage'),
('think over something; ponder','','Cogitate'),
('gentle and easily lead','','Docile'),
('fake; false','','Fraudulent'),
('unfeeling','','Insentient'),
('environment','','Milieu'),
('in a thoughtful mood; thinking deeply','','Pensive'),
('steal','','Purloin'),
('still; not moving','','Stagnant'),
('dizziness','','Vertigo'),
('perceptive; sharp-witted','','Astute'),
('picture made from fragments of other pictures','','Collage'),
('having stubbornly held opinions','','Dogmatic'),
('not serious','','Frivolous'),
('dull; bland; boring','','Insipid'),
('swamp; muddy ground','','Mire'),
('poverty','','Penury'),
('cowardly','','Pusillanimous'),
('dull; sober; serious','','Staid'),
('not developed','','Vestigial'),
('place of refuge or safety','','Asylum'),
('arrange in order','','Collate'),
('stupid person','','Dolt'),
('economical; not wasting anything','','Frugal'),
('to start; provoke','','Instigate'),
('hater of the rest of mankind','','Misanthrope'),
('observant','','Perceptive'),
('compulsion to start fires','','Pyromania'),
('section of a poem','','Stanza'),
('small sketch','','Vignette'),
('person who does not believe in God','','Atheist'),
('local and informal (used of language)','','Colloquial'),
('foolish old man','','Dotard'),
('groove','','Furrow'),
('troublemaker; person who entices others to do something','','Instigator'),
('wrong name','','Misnomer'),
('perceptive; insightful','','Percipient'),
('drink down quickly','','Quaff'),
('loyal; faithful; dependable','','Staunch'),
('blackening someone''s name','','Vilification'),
('waste away from lack of use','','Atrophy'),
('plotting and planning','','Collusion'),
('speak slowly with words running together','','Drawl'),
('hidden and secret','','Furtive'),
('a rebel','','Insurgent'),
('hater of women','','Misogynist'),
('damnation','','Perdition'),
('marsh; bog','','Quagmire'),
('fixed image','','Stereotype'),
('prove right; remove blame','','Vindicate'),
('weaken','','Attenuate'),
('take possession of','','Commandeer'),
('nonsense','','Drivel'),
('useless; hopeless','','Futile'),
('never-ending','','Interminable'),
('deliberately deceiving','','Misrepresentation'),
('in a commanding manner','','Peremptory'),
('picturesque','','Quaint'),
('dockworker','','Stevedore'),
('an accomplished musician','','Virtuoso'),
('increase; make bigger','','Augment'),
('self-satisfied; smug','','Complacent'),
('dryly amusing','','Droll'),
('ancient type of sailing ship','','Galleon'),
('sporadic; irregular','','Intermittent'),
('lessen; make less severe','','Mitigate'),
('treachery','','Perfidy'),
('dilemma; puzzle','','Quandary'),
('suppress','','Stifle'),
('dangerous; harmful','','Virulent'),
('favorable; promising to turn out well','','Auspicious'),
('easy to control; submissive','','Compliant'),
('1. monotonous noise ','','Drone'),
('; 2. to speak with no emotion ','','Gambol'),
('; 3.male bee','','Intransigence'),
('frolic; leap; bound','','Modicum'),
('stubbornness','','Perfunctory'),
('small amount','','Quarantine'),
('superficial; cursory','','Stoic'),
('isolation to prevent the spread of disease','','Vital'),
('known for fortitude; indifferent to pleasure or pain','','Austere'),
('essential; alive; important','','Concatenate'),
('severely plain','','Dubious'),
('link together','','Garble'),
('doubtful','','Intransigent'),
('distort; confuse; muddle','','Momentous'),
('stubborn; unyielding','','Peripatetic'),
('very important','','Quarry'),
('nomadic; moving from place to place','','Stoke'),
('1. something that is hunted; 2. mine for stone','','Vitriolic'),
('add fuel to; strengthen','','Aversion'),
('corrosive; strongly attacking','','Concatenation'),
('a dislike of','','Dupe'),
('linking into chains','','Garish'),
('to fool someone','','Intrepid'),
('gaudy','','Monotonous'),
('brave','','Peripheral'),
('dull; unvarying','','Querulous'),
('on the edge; not important','','Stolid'),
('always complaining','','Vivacity'),
('impassive; dull; indifferent','','Balk'),
('liveliness; animation','','Conciliate'),
('hinder and prevent; hesitate over','','Dynamic'),
('to bring together; end a dispute','','Garner'),
('lively; vibrant; energetic','','Inveterate'),
('gather; collect','','Moratorium'),
('habitual','','Perjury'),
('temporary prohibition or halt to activity','','Quirk'),
('telling lies under oath','','Stratagem'),
('oddity','','Vivify'),
('plot; plan; trick','','Banal'),
('enliven','','Concise'),
('common; dull','','Ebullient'),
('stated in few words','','Garrulous'),
('very lively; cheerful; jovial; happy','','Invidious'),
('talkative','','Moribund'),
('arousing envy','','Pernicious'),
('on the point of death','','Ramble'),
('destructive; harmful','','Strident'),
('wander aimlessly','','Vociferous'),
('loud and harsh','','Banality'),
('noisy; loud in speech','','Condescend'),
('ordinariness; dullness','','Eccentric'),
('talk down to','','Gaunt'),
('unusual; quirky; odd','','Inviolable'),
('emaciated; bony and angular','','Morose'),
('cannot be invaded','','Persnickety'),
('gloomy; bad tempered','','Ramifications'),
('fastidious; fussy','','Stringent'),
('branches; subdivisions of a complex system; outcomes','','Volatile'),
('troublesome influence','','Bane'),
('tacitly support; overlook','','Condone'),
('taking things from different sources','','Eclectic'),
('a category; type','','Genre'),
('easily angered','','Irascible'),
('ordinary; worldly','','Mundane'),
('caused to continue','','Perpetuated'),
('resentment; animosity; bad feeling','','Rancor'),
('swagger; show off','','Strut'),
('talkative','','Voluble'),
('poet','','Bard'),
('overlooking; disregarding; ignoring','','Condoning'),
('building; structure; construction','','Edifice'),
('relevant','','Germane'),
('anger [','','Ire'),
(' = very angry]','','Munificent'),
('generous; charitable','','Perpetuity'),
('eternity','','Rant'),
('use bombastic language','','Stupefying'),
('astonishing; shocking; stunning into silence','','Voluminous'),
('very large; spacious','','Bastion'),
('fortress; stronghold','','Conflagration'),
('big fire','','Efface'),
('wipe out; remove all trace of','','Germinal'),
('just growing; not developed; immature','','Irksome'),
('annoying; infuriating','','Mutinous'),
('very rebellious','','Personable'),
('attractive','','Ratify'),
('approve; consent','','Subpoena'),
('summons to court','','Voracious'),
('ravenous','','Befuddle'),
('confuse','','Confound'),
('confuse','','Effigy'),
('a model of a person','','Gibbering'),
('making meaningless noises','','Ironic'),
('satiric; unexpected','','Myriad'),
('in large numbers','','Perspicacious'),
('insightful; sharp; wise','','Raucous'),
('rough and unpleasant (of sounds)','','Substantiate'),
('give supporting evidence','','Waive'),
('surrender; give up','','Begrudge'),
('resent','','Congeal'),
('to solidify','','Effusive'),
('gushing; demonstrative','','Glacial'),
('hostile; unfriendly; cold; icy','','Irrational'),
('unreasonable; absurd','','Navigable'),
('suitable for sailing','','Perspicacity'),
('insight','','Raze'),
('destroy; demolish; tear down','','Subterfuge'),
('a trick','','Wane'),
('grow less','','Beguile'),
('mislead; lure','','Congenital'),
('present from birth','','Egalitarianism'),
('belief in equality','','Goad'),
('prod; urge','','Irreproachable'),
('cannot be criticized; perfect','','Nebulous'),
('vague','','Pertinent'),
('relevant','','Rebuttal'),
('denial','','Subtle'),
('not obvious','','Wary'),
('hesitant; cautious','','Belabor'),
('explain in unnecessary detail','','Connoisseur'),
('person with refined taste and good judgment','','Egregious'),
('outstandingly\, obviously bad','','Grate '),
('1. to annoy; aggravate; vex; 2. shred','','Irrevocable'),
('cannot be cancelled; unchangeable','','Nefarious'),
('wicked; immoral; disreputable','','Peruse'),
('read carefully','','Recant'),
('disclaim; retract statement','','Subversive'),
('rebellious; revolutionary','','Wax'),
('to increase; to grow','','Beleaguer'),
('besiege; attack','','Consecrate'),
('dedicate','','Egress'),
('exit','','Gratis'),
('free of charge; without payment','','Itinerant'),
('nomadic; wandering from place to place','','Negate'),
('cancel; deny','','Pervasive'),
('spreading everywhere','','Recapitulate'),
('summarize','','Succinct'),
('concise','','Waylay'),
('accost; stop; approach; hinder','','Belie'),
('contradict','','Consensus'),
('general agreement','','Eloquent'),
('fluent and persuasive in speech','','Gratuitous'),
('unwarranted','','Jaded'),
('tired; bored; worn out','','Negligence'),
('carelessness','','Petrify'),
('1. terrify; 2. turn to stone','','Receptacle'),
('container; vessel; holder','','Suffragist'),
('someone who campaigns for voting rights','','Weighty'),
('serious','','Belittle'),
('to demean','','Conspicuous'),
('easily seen; prominent','','Elucidate'),
('make clear','','Gravity'),
('seriousness','','Jargon'),
('specialized language used by experts','','Neologism'),
('newly coined word','','Petulant'),
('sulky; peevish','','Recluse'),
('someone who cuts himself off from life','','Supercilious'),
('proud and haughty','','Whelp'),
('war-like; aggressive','','Bellicose'),
('complete; total; supremely good','','Consummate'),
('hard to pin down','','Elusive'),
('extroverted; sociable; outgoing','','Gregarious'),
('cynical; pessimistic','','Jaundiced'),
('annoy','','Nettle'),
('an event or happening (plural: phenomena)','','Phenomenon'),
('get better after illness','','Recuperate'),
('extremely good; the best','','Superlative'),
('sharpen','','Whet'),
('aggressive; ready to fight','','Belligerent'),
('living or happening at the same time','','Contemporary'),
('very thin; withered','','Emaciated'),
('coarse; granular','','Gritty'),
('short pleasure trip','','Jaunt'),
('miserly; stingy','','Niggardly'),
('charity; love of mankind','','Philanthropy'),
('formalities; paperwork; official procedure','','Red tape'),
('grumpy; rude','','Surly'),
('capricious; changeable','','Whimsical'),
('complain about','','Bemoan'),
('sorry','','Contrite'),
('set free','','Emancipate'),
('sudden loud laughter','','Guffaw'),
('put at risk; endanger','','Jeopardize'),
('wandering from place to place','','Nomadic'),
('uncultured person','','Philistine'),
('smelling of; giving off odors','','Redolent'),
('secret; sneaky; stealthy','','Surreptitious'),
('stubborn','','Willful'),
('kindly','','Benevolent'),
('sorrow and repentance','','Contrition'),
('defraud; steal','','Embezzle'),
('cunning; craftiness','','Guile'),
('extremely patriotic; nationalistic','','Jingoistic'),
('an appearance of indifference; calm and composed','','Nonchalance'),
('calm; imperturbable','','Phlegmatic'),
('put right something that was wrong','','Redress'),
('secretly; furtively; stealthily','','Surreptitiously'),
('cunning','','Wily'),
('kindly; harmless','','Benign'),
('stubborn','','Contumacious'),
('involve in hostility or argument','','Embroil'),
('frank; straightforward; honest','','Guileless'),
('in a joking manner','','Jocular'),
('having no special features; dull and ordinary','','Nondescript'),
('plunder','','Pillage'),
('unnecessary; superfluous','','Redundant'),
('vulnerable','','Susceptible'),
('flimsy; frail; delicate','','Wispy'),
('compassion; gentleness; fondness','','Benignity'),
('a bruise','','Contusion'),
('come out; appear','','Emerge'),
('unwariness; trustfulness; being easily fooled','','Gullibility'),
('gaiety; happiness','','Jollity'),
('a person of no importance; not famous','','Nonentity'),
('topmost point','','Pinnacle'),
('public vote','','Referendum'),
('doubtful','','Suspect'),
('melancholy; pensive; expressing a longing for','','Wistful'),
('leave something in one''s will to be given after one''s death','','Bequeath'),
('a puzzle','','Conundrum'),
('to imitate something admired','','Emulate'),
('easily fooled','','Gullible'),
('ecstatic; delighted; rejoicing','','Jubilant'),
('longing for the past','','Nostalgia'),
('very religious','','Pious'),
('disprove','','Refute'),
('lover of luxury','','Sybarite'),
('crazy; wacky','','Zany'),
('scold; criticize','','Berate'),
('usual; customary; common','','Conventional'),
('give support or approval to','','Endorse'),
('concerned with the sense of taste','','Gustatory'),
('correct in judgment; wise','','Judicious'),
('infamy; known for wrong doing','','Notoriety'),
('of central importance','','Pivotal'),
('entertain','','Regale'),
('bootlicker; flatterer','','Sycophant'),
('enthusiasm','','Zeal'),
('type of cap','','Beret'),
('fat','','Corpulent'),
('staying power; patience; stamina','','Endurance'),
('common and over-used','','Hackneyed'),
('science or study of law','','Jurisprudence'),
('new; unusual','','Novel'),
('pacify; soothe; calm','','Placate'),
('dismiss to a lower position','','Relegate'),
('quiet; saying little','','Taciturn'),
('fanatic','','Zealot'),
('behaving like a beast; brutal','','Bestial'),
('highly folded','','Corrugated'),
('lasting','','Enduring'),
('worshipped; consecrated','','Hallowed'),
('place next to','','Juxtapose'),
('a beginner; tyro','','Novice'),
('harmless medicine with no effect; dummy medicine','','Placebo'),
('regret; sorrow; contrition','','Remorse'),
('concerned with the sense of touch','','Tactile'),
('summit','','Zenith');